ASoC: wcd9304: Remove duplicated code
This was moved to mfd.

Fixes:
  sound/soc/codecs/wcd9304.c:74:8: error: redefinition of 'struct sitar_codec_dai_data'

Change-Id: I14f8a9cf2e82022b013b92dd00f1ca9c9fd9ec09
Signed-off-by: Luis Cruz <ljc2491@gmail.com>