drivers: video: mdp4: Fix building with gcc-4.8+
Since the minimum_[ab/ib] are of the unsigned 64-bit type, the
following build errors can be  bypassed (and the div function
possibly optimized) by using div_u64.

The API also notes that "This is the most common 64bit divide and
should be used if possible[...]"

Fixes errors:
 ../video/msm/mdp4_overlay.c:3242: undefined reference to `__aeabi_uldivmod'
 ../video/msm/mdp4_overlay.c:3244: undefined reference to `__aeabi_uldivmod'

Change-Id: I805b8916e7cff5da566ca4fea98c8b18fa56fdb1